### ISSUE TITLE
WARNING:paperscraper.load_dumps: No dump found for biorxiv. Skipping entry.

### ISSUE THREAD

**Issue by qingpowuwu** [ur-whitelab/chemcrow-public#11]
Dear Sir

Upon executing the python test_agent.py command, I encountered the following warnings:

```
    WARNING:paperscraper.load_dumps: No dump found for biorxiv. Skipping entry.
    WARNING:paperscraper.load_dumps: No dump found for chemrxiv. Skipping entry.
    WARNING:paperscraper.load_dumps: No dump found for medrxiv. Skipping entry.
    WARNING:paperscraper.load_dumps: No dumps found for either biorxiv or medrxiv. Consider using paperscraper.get_dumps.* to fetch the dumps.
```

Could you please assist me in resolving this issue? It appears that the necessary data dumps are missing, and I am unsure how to proceed with using paperscraper.get_dumps.* to retrieve them.

Thanks!

**Comment by SamCox822** [comment]
This is an issue with paper scraper and has been since solved

**Comment by AmT42** [comment]
I have the same issue
