### ISSUE TITLE
Add paperqa :)

### ISSUE THREAD

**Issue by doncamilom** [ur-whitelab/chemcrow-public#16]

**Comment by HannibaltheArrow** [comment]
I was also thinking this. May I ask, is there a reason paperQA wasn't included in the public chemcrow repository? If I remember the paper correctly, the lit search tool already uses paperQA.

**Comment by SamCox822** [comment]
> I was also thinking this. May I ask, is there a reason paperQA wasn't included in the public chemcrow repository? If I remember the paper correctly, the lit search tool already uses paperQA.

We were updating versions and dependencies and had not added it yet. PR to fix this now
