### ISSUE TITLE
Paperscraper not in requirements. LitSearch tool fails

### ISSUE THREAD

**Issue by fran-mora** [ur-whitelab/chemcrow-public#7]
paperscraper is not in requirements, so your sample code fails with:

```
[/usr/local/lib/python3.10/dist-packages/chemcrow/tools/search.py](https://localhost:8080/#) in <module>
      3 import paperqa
      4 import langchain
----> 5 import paperscraper
      6 from langchain.tools import BaseTool
      7 from langchain import SerpAPIWrapper, OpenAI

ModuleNotFoundError: No module named 'paperscraper'
```

When installing the latest version, I get:
`AttributeError: module 'paperscraper' has no attribute 'search_papers'`

What version of paperscraper are you using?

**Comment by doncamilom** [comment]
Hi there,

Solved in [v0.3.17](https://github.com/ur-whitelab/chemcrow-public/tree/v0.3.17). Thanks for raising the issue!
