### ISSUE TITLE
pip install chemcrow gives version 0.2.0 instead of 0.3.0

### ISSUE THREAD

**Issue by astella5** [ur-whitelab/chemcrow-public#8]
https://pypi.org/project/chemcrow/

![image](https://github.com/ur-whitelab/chemcrow-public/assets/66842245/5cc6402a-4e13-4f18-a574-cb83c946bd82)

**Comment by doncamilom** [comment]
fixed, thanks for pointing it out.
current v0.3.7 should work fine
